### ISSUE TITLE
Deletes existing properties if existing value of `className` is falsey

### ISSUE THREAD

**Issue by lpsinger** [riderjensen/rehype-class-names#1]
Due to this line:

```ts
if (!elem?.properties?.className) elem.properties = { className };
```

this package deletes other existing properties if `className` is initially falsey (undefined, null, or an empty string). For example, this wipes out the `href` attribute from `a` elements.

See, for example, https://github.com/nasa-gcn/gcn.nasa.gov/pull/1209.

**Comment by riderjensen** [comment]
Hey @lpsinger , thanks for bringing this to my attention. I have just pushed a commit and bumped the package in npm which, as far as I can tell, fixes the issue. I also created a test file which has a few different test cases that I am now testing for. If you bump to `1.0.12` which is live on [NPM](https://www.npmjs.com/package/rehype-class-names) than I believe you should be good to go. Let me know if you have any issues :)
