### ISSUE TITLE
classNames should be an array of strings

### ISSUE THREAD

**Issue by lpsinger** [riderjensen/rehype-class-names#2]
According to https://github.com/rehypejs/rehype/pull/146#discussion_r1285584481, `classNames` should be an array of strings.

My interpretation of the rehype documentation is that it can _either_ be a string or an array of strings. rehype-add-classes should probably gracefully handle the case that `classNames` is initially undefined or an empty string, a non-empty string, or an array of strings.

I am not 100% clear on what type @woorm wants the final value of `classNames` to be, but probably an array of strings.

**Comment by riderjensen** [comment]
Hey @lpsinger I just upgraded the code as per @wooorm suggestion to use https://github.com/syntax-tree/hast-util-classnames which makes this package much more usable. Feel free to upgrade to v1.0.13

**Comment by lpsinger** [comment]
Thanks!
