### ISSUE TITLE
Package update to use unified v11

### ISSUE THREAD

**Issue by artello73** [riderjensen/rehype-class-names#3]
Hello,

Thanks a lot for a nice package, but when I tried to use it with latest unified version ( 11.0.4 as of today) it gives a bunch of typescript errors.  Any chance to get this package updated?

**Comment by riderjensen** [comment]
Hello, happy to take a look at doing that. On my local, I have bumped the version of unified to 11.0.4 and run the test suite and I am not seeing any typescript errors. Can you include the typescript errors and, if possible, a link to the project where you are seeing these issues?

Edit: I just tried in another project and I can reproduce the errors. Let me take a look and get back to you

**Comment by riderjensen** [comment]
I have just released version 2.0.0 of this package which bumped the unified version to 11. I tested it in a project and there were no type errors upon building. This should solve your issue, let me know if you run into any other problems
